/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include <stdint.h>
// register address

#define GPIOA_BASE 0x40010800

#define GPIOA_CRH *(volatile uint32_t *)(GPIOA_BASE + 0x04)
#define GPIOA_CRL *(volatile uint32_t *)(GPIOA_BASE + 0x00)

#define GPIOA_ODR *(volatile uint32_t *)(GPIOA_BASE + 0x0C)

// RCC - clock control register base:
#define RCC_Base 0x40021000
#define RCC_APB2ENR *(volatile uint32_t *)(RCC_Base + 0x18)
#define RCC_CFGR *(volatile uint32_t *)(RCC_Base + 0x04)
#define RCC_CR *(volatile uint32_t *)(RCC_Base + 0x0)

// External Interrupt
#define EXTI_Base 0x40010400
#define EXTI_IMR *(volatile uint32_t *)(EXTI_Base + 0x0)
#define EXTI_RTSR *(volatile uint32_t *)(EXTI_Base + 0x08)
#define EXTI_PR *(volatile uint32_t *)(EXTI_Base + 0x14)

// Alternative Function I/O Register Base
#define AFIO_Base 0x40010000
// External interrupt configuration register 1 (AFIO_EXTICR1)
#define AFIO_EXTICR1 *(volatile uint32_t *)(AFIO_Base + 0x08)

// NVIC BASE
#define NVIC_EXTIE0 *(volatile uint32_t*)(0xE000E100)


void clockInit(void) {
	RCC_APB2ENR |= (1 << 2);
	// Enabling Clock For AFIO Register
	RCC_APB2ENR |= (1 << 0);
}

void gpioInit(void) {
	// Pin_13 PORTA As Output.
	GPIOA_CRH &= 0xFF0FFFFF;
	GPIOA_CRH |= 0x00200000;

	// Pin_0 PORTA As Input: Floating Input (Floating means it's not connected with anything as we will connect it with a push button).
	GPIOA_CRL |= (1<<2);
}

int val1 = 0;
int val2 = 10;
int val3 = 0;

unsigned int controlReg = 0;
unsigned int IPSR_Reg = 0;

int main(void)
{
	__asm("nop");
	__asm("nop");
	__asm("nop");


// Move the value 255 into val variable.
	__asm("mov %0, #0xff"
		  :	"=r"(val1)); // Output Parameter

// Move the value of val variable into R0 general purpose register.
	__asm("mov R0, %0"
		   :
		   : "r" (val1)); // Input parameter

// Add the values of val1 and val2 and store it in val3.
	__asm("add %0, %1, %2"
			: "=r"(val3)
			: "r"(val1), "r"(val2));

// Read the value of Control Register while CPU in Thread MODE.

	__asm("MRS %[out0], CONTROL"
		   :[out0] "=r" (controlReg));

	__asm("nop");
	__asm("nop");
	__asm("nop");
	clockInit();
	gpioInit();
	// EXTI0 configuration to PORTA0
	AFIO_EXTICR1 = 0;
	// Mask Line 0
	EXTI_IMR |= (1<<0);
	// Rising Trigger Enabled For Line 0
	EXTI_RTSR |= (1<<0);
	// Enable NVIC Irq6(from Interrupt Vector Table)   <<>> EXTI0
	NVIC_EXTIE0 |= (1 << 6);

	while(1);
}

void EXTI0_IRQHandler() {
	__asm("MRS %[out0], IPSR"
		   :[out0] "=r" (IPSR_Reg));
	// Toggle Pin_13 At GPIOA
	GPIOA_ODR ^= (1 << 13);

	// Stop the interrupt request.
	EXTI_PR |= (1 << 0);
}
